### ISSUE TITLE
请问该怎么拿到G2对象？

### ISSUE THREAD

**Issue by ding-kai** [cipchk/g2-angular#1]

**Comment by simplejason** [comment]
可以试试在需要的地方 declare const G2: any;
G2对象应该是在引入js时实现全局对象，官方介绍：https://antv.alipay.com/g2/api/index.html

**Comment by cipchk** [comment]
见 `(ready)` 事件，[DEMO代码](https://github.com/cipchk/g2-angular/blob/master/demo/src/app/components/area.component.ts#L39)
